table financials
	lineageTag: 0da170f4-0f77-4486-b8db-e581756ffdc5

	measure 'Total Profit' = SUM(financials[Profit])
		lineageTag: 5e4d96bd-e582-4f3e-b307-073ce911b3ad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Profit YTD' =
			
			IF(
				ISFILTERED('financials'[Date]),
				ERROR("Time intelligence quick measures can only be grouped or filtered by the Power BI-provided date hierarchy or primary date column."),
				TOTALYTD([Total Profit], 'financials'[Date].[Date])
			)
		lineageTag: 811093de-4c67-43d2-897e-84d73713f7f3

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "YearToDate"
				}

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Segment
		dataType: string
		lineageTag: 1189122b-8371-4f0f-b228-83611876ede8
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 2ccd851b-452c-40dd-bced-b70ff4b7da9b
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: d640f877-6dd3-4c4f-aa93-742b55c5f85e
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Discount Band'
		dataType: string
		lineageTag: e3ab96ad-a0c7-40bb-848c-05f97b91416e
		summarizeBy: none
		sourceColumn: Discount Band

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: double
		lineageTag: 3de6f9b4-3118-41a9-a129-0ecf7f560c0f
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Manufacturing Price'
		dataType: int64
		formatString: 0
		lineageTag: c7354431-f490-40fd-b214-b6c7187e0c0d
		summarizeBy: sum
		sourceColumn: Manufacturing Price

		annotation SummarizationSetBy = Automatic

	column 'Sale Price'
		dataType: int64
		formatString: 0
		lineageTag: e9e40f60-060d-4680-b24a-e25ace97bc28
		summarizeBy: sum
		sourceColumn: Sale Price

		annotation SummarizationSetBy = Automatic

	column 'Gross Sales'
		dataType: double
		lineageTag: 35ff797c-ab0b-4ac7-9a05-2fa0518e6220
		summarizeBy: sum
		sourceColumn: Gross Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discounts
		dataType: double
		lineageTag: 3ad3713e-b2b4-408a-96cf-46e60f9ede91
		summarizeBy: sum
		sourceColumn: Discounts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sales
		dataType: double
		lineageTag: d4729627-4cbb-4123-9464-2be33244134f
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COGS
		dataType: double
		lineageTag: bc0ccff9-f04f-4ff7-b1ec-d2ff78f894a7
		summarizeBy: sum
		sourceColumn: COGS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 0fa8d65c-b32f-4837-84b2-f5e25bc2db39
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b6628c7c-23a3-4b13-ad42-2dc0d6f708c7
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 0ed35dc3-4b7b-40ad-8cab-485c9854cccd
			defaultHierarchy: LocalDateTable_b4f9c290-b568-4d8d-ba69-4d989fafb575.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: b28fa509-97ee-4eb7-b714-44b60fdbb7d7
		summarizeBy: sum
		sourceColumn: Month Number

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 202596e0-e3f8-4284-85e6-00a405fb7841
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: ffa2e6a4-879a-46a4-b1ee-77415524f82c
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'new Column' = financials[Units Sold]*financials[Manufacturing Price]
		lineageTag: 1ac0e092-c0d6-4f91-8ab9-9a945d0ab014
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition financials = m
		mode: import
		source =
				let
				 Source = Excel.Workbook(File.Contents("C:\Program Files\Microsoft Power BI Desktop\bin\SampleData\Financial Sample.xlsx"), null, true),
				    financials_Table = Source{[Item="financials",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(financials_Table,{{"Segment", type text}, {"Country", type text}, {"Product", type text}, {"Discount Band", type text}, {"Units Sold", type number}, {"Manufacturing Price", Int64.Type}, {"Sale Price", Int64.Type}, {"Gross Sales", type number}, {"Discounts", type number}, {"Sales", type number}, {"COGS", type number}, {"Profit", type number}, {"Date", type date}, {"Month Number", Int64.Type}, {"Month Name", type text}, {"Year", Int64.Type}})
				in
				 #"Changed Type"

	annotation PBI_ResultType = Table

